import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { buildComment, buildSummary, headline, COMMENT_MARKER } from '../scripts/build-comment.mjs';

/** A `check --json` payload, clean unless overridden. */
function report(overrides = {}) {
  const counts = {
    current: 96,
    behind: 0,
    edited: 0,
    missing: 0,
    added: 0,
    orphaned: 0,
    ...(overrides.counts ?? {}),
  };
  return {
    schema: 1,
    project: 'checkout-web',
    generatorVersion: { recorded: '1.2.0', installed: '1.2.0' },
    behind: [],
    edited: [],
    missing: [],
    added: [],
    orphaned: [],
    newAiTools: [],
    severity: 'none',
    failOn: 'none',
    ok: true,
    ...overrides,
    counts,
  };
}

describe('headline', () => {
  test('says so plainly when nothing has drifted', () => {
    assert.equal(headline(report()), 'AI rules are current');
  });

  test('pluralises, because "1 files" in a bot comment reads as a bug', () => {
    assert.equal(headline(report({ counts: { behind: 1 } })), 'AI rules: 1 file behind');
    assert.equal(headline(report({ counts: { behind: 3 } })), 'AI rules: 3 files behind');
  });

  test('names every non-empty bucket', () => {
    const h = headline(report({ counts: { behind: 2, orphaned: 1, missing: 1, added: 4 } }));
    assert.match(h, /2 files behind/);
    assert.match(h, /1 orphaned file/);
    assert.match(h, /1 file missing/);
    assert.match(h, /4 new files/);
  });
});

describe('buildComment', () => {
  test('posts nothing for a clean repo', () => {
    // A bot that comments on every green PR to say "nothing to report" is a
    // bot people mute.
    assert.equal(buildComment(report()), null);
  });

  test('updates an existing comment to the all-clear once drift is fixed', () => {
    const body = buildComment(report(), { editingExisting: true });
    assert.ok(body);
    assert.match(body, /AI rules are current/);
  });

  test('keeps every block separated by a blank line, so Markdown does not fold them', () => {
    // Two adjacent non-empty lines become one paragraph, which silently ran
    // the all-clear sentence into the trailing note.
    for (const body of [
      buildComment(report({ counts: { edited: 1 }, edited: ['a.mdc'] }), { editingExisting: true }),
      buildComment(report({ counts: { behind: 1, edited: 1 }, behind: ['a.mdc'], edited: ['b.mdc'] })),
    ]) {
      const lines = body.split('\n');
      const subIndex = lines.findIndex((l) => l.startsWith('<sub>'));
      assert.ok(subIndex > 0);
      assert.equal(lines[subIndex - 1], '', `expected a blank line before: ${lines[subIndex]}`);
    }
  });

  test('always carries the marker, so the comment stays sticky', () => {
    const body = buildComment(report({ counts: { behind: 1 }, behind: ['a.mdc'] }));
    assert.ok(body.startsWith(COMMENT_MARKER));
  });

  test('lists drifted files and the command that fixes them', () => {
    const body = buildComment(
      report({
        counts: { behind: 2 },
        behind: ['.cursor/rules/nextjs.mdc', '.claude/skills/nextjs/SKILL.md'],
      }),
    );
    assert.match(body, /`\.cursor\/rules\/nextjs\.mdc`/);
    assert.match(body, /npx ai-project-bootstrap upgrade/);
  });

  test('truncates a long list rather than pasting hundreds of paths', () => {
    const files = Array.from({ length: 25 }, (_, i) => `.cursor/rules/mod-${i}.mdc`);
    const body = buildComment(report({ counts: { behind: 25 }, behind: files }));
    assert.match(body, /…and 15 more/);
    assert.ok(!body.includes('mod-20'));
  });

  test('states edited files as a guarantee, never as something to fix', () => {
    const body = buildComment(
      report({ counts: { behind: 1, edited: 2 }, behind: ['a.mdc'], edited: ['b.mdc', 'c.mdc'] }),
    );
    assert.match(body, /2 files you edited are preserved and will not be touched/);
    // Nothing in the comment should read as an instruction to revert them.
    assert.ok(!/revert/i.test(body));
  });

  test('does not promise upgrade will remove an orphan', () => {
    const body = buildComment(
      report({ counts: { orphaned: 1 }, orphaned: ['.cursor/rules/firebase.mdc'] }),
    );
    assert.match(body, /will not remove orphaned files/);
    // Orphans alone are not fixable by upgrade, so the command must not appear.
    assert.ok(!body.includes('npx ai-project-bootstrap upgrade\n```'));
  });

  test('offers upgrade when something it can fix sits alongside an orphan', () => {
    const body = buildComment(
      report({ counts: { behind: 1, orphaned: 1 }, behind: ['a.mdc'], orphaned: ['b.mdc'] }),
    );
    assert.match(body, /npx ai-project-bootstrap upgrade/);
    assert.match(body, /will not remove orphaned files/);
  });

  test('names both versions when the project was generated by an older release', () => {
    const body = buildComment(
      report({
        counts: { behind: 1 },
        behind: ['a.mdc'],
        generatorVersion: { recorded: '1.0.0', installed: '1.2.0' },
      }),
    );
    assert.match(body, /generated with v1\.0\.0, checked against v1\.2\.0/);
  });

  test('copes with a project generated before versions were recorded', () => {
    const body = buildComment(
      report({
        counts: { behind: 1 },
        behind: ['a.mdc'],
        generatorVersion: { recorded: null, installed: '1.2.0' },
      }),
    );
    assert.match(body, /checked against v1\.2\.0/);
    assert.ok(!body.includes('null'));
  });
});

describe('buildSummary', () => {
  test('reports every bucket, including the empty ones', () => {
    const summary = buildSummary(report({ counts: { behind: 2, edited: 1 } }));
    assert.match(summary, /\| Behind \| 2 \|/);
    assert.match(summary, /\| Orphaned \| 0 \|/);
    assert.match(summary, /\| Edited \(preserved\) \| 1 \|/);
    assert.match(summary, /checkout-web/);
  });
});

/**
 * Advisories, added in the CLI release that made `critical` reachable.
 *
 * The `report()` helper above deliberately produces a payload with **no**
 * `advisories` field at all — which is exactly what a CLI too old to know about
 * them emits. Every pre-existing test in this file therefore doubles as the
 * old-payload compatibility test, and the ones below only have to cover what is
 * new.
 */
function advisory(overrides = {}) {
  return { id: 'supabase-auth-v2', severity: 'warning', publishedAt: '2026-01-15', ...overrides };
}

function withAdvisories(items, entitled = true, overrides = {}) {
  return report({ ...overrides, advisories: { entitled, total: items.length, items } });
}

describe('advisories', () => {
  test('renders nothing at all for a CLI too old to report them', () => {
    // No `advisories` key whatsoever — the shape every released CLI emits today.
    const body = buildComment(report({ counts: { behind: 1 }, behind: ['docs/setup.md'] }));
    assert.ok(!body.includes('Advisories'));
    assert.ok(body.includes('docs/setup.md'));
  });

  test('renders nothing when the CLI looked and found none', () => {
    const body = buildComment(
      withAdvisories([], true, { counts: { behind: 1 }, behind: ['docs/setup.md'] }),
    );
    assert.ok(!body.includes('Advisories'));
  });

  test('treats an explicit null as not asked', () => {
    const body = buildComment(
      report({ advisories: null, counts: { behind: 1 }, behind: ['docs/setup.md'] }),
    );
    assert.ok(!body.includes('Advisories'));
  });

  test('shows the summary and links the source when entitled', () => {
    const body = buildComment(
      withAdvisories([
        advisory({ summary: 'Supabase Auth moved a method in v2.', url: 'https://example.com/a' }),
      ]),
    );

    assert.ok(body.includes('**Advisories** — 1 known vendor change'));
    assert.ok(body.includes('[Supabase Auth moved a method in v2.](https://example.com/a)'));
    assert.ok(body.includes('`warning`'));
  });

  /** One line, no pitch. This lands in somebody's pull request. */
  test('shows ids and one quiet line when not entitled', () => {
    const body = buildComment(
      withAdvisories([advisory({ severity: 'critical' })], false),
    );

    assert.ok(body.includes('`critical`'));
    assert.ok(body.includes('`supabase-auth-v2`'));
    assert.ok(body.includes('ai-project-bootstrap login'));
    // Never the text, and never more than one line about subscribing.
    assert.equal(body.split('\n').filter((l) => l.includes('subscription')).length, 1);
  });

  /**
   * A repository whose files are all current but whose vendor just shipped a
   * breaking change is not "clean" in any sense the reader cares about.
   */
  test('posts a comment on a file-clean repo when an advisory applies', () => {
    const body = buildComment(withAdvisories([advisory()]));

    assert.ok(body !== null);
    assert.ok(body.includes(COMMENT_MARKER));
    assert.ok(body.includes('**Advisories**'));
  });

  test('says so in the headline rather than claiming everything is current', () => {
    assert.equal(
      headline(withAdvisories([advisory(), advisory({ id: 'other' })])),
      'AI rules are current · 2 advisories',
    );
    assert.equal(headline(withAdvisories([advisory()])), 'AI rules are current · 1 advisory');
    assert.equal(headline(report()), 'AI rules are current');
  });

  test('appends to a drift headline rather than replacing it', () => {
    assert.equal(
      headline(withAdvisories([advisory()], true, { counts: { behind: 2 } })),
      'AI rules: 2 files behind, 1 advisory',
    );
  });

  test('caps the list and says how many were left out', () => {
    const many = Array.from({ length: 8 }, (_, i) => advisory({ id: `a-${i}`, summary: `Note ${i}` }));
    const body = buildComment(withAdvisories(many));

    assert.ok(body.includes('…and 3 more'));
    assert.ok(body.includes('Note 4'));
    assert.ok(!body.includes('Note 5'));
  });

  test('adds a summary row only when the CLI reported them', () => {
    assert.ok(!buildSummary(report()).includes('Advisories'));
    assert.ok(buildSummary(withAdvisories([advisory()])).includes('| Advisories | 1 |'));
  });
});

/**
 * Fleet reporting.
 *
 * `reportToFleet` lives in `run.mjs`, which is the half that touches the
 * network and the runner — so these drive it the way the runner does, through
 * the environment, with `fetch` stubbed. What matters is not the request shape
 * (the backend has its own tests for that) but that **no failure here can fail
 * a job**: the check already ran, and a dashboard being unreachable says
 * nothing about whether the rules have drifted.
 */
describe('reportToFleet', () => {
  const originals = {
    APB_REPORT_TO: process.env.APB_REPORT_TO,
    APB_ORG_TOKEN: process.env.APB_ORG_TOKEN,
    GITHUB_REPOSITORY: process.env.GITHUB_REPOSITORY,
  };
  let written;
  let realWrite;
  let realFetch;

  function capture() {
    written = [];
    realWrite = process.stdout.write.bind(process.stdout);
    process.stdout.write = (chunk) => {
      written.push(String(chunk));
      return true;
    };
    realFetch = globalThis.fetch;
  }

  function restore() {
    process.stdout.write = realWrite;
    globalThis.fetch = realFetch;
    for (const [key, value] of Object.entries(originals)) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }

  /** Imported fresh each time so the module reads the current environment. */
  async function load() {
    const module = await import(`../scripts/run.mjs?fleet=${Math.random()}`);
    return module;
  }

  test('does nothing at all when report-to is unset', async () => {
    capture();
    try {
      delete process.env.APB_REPORT_TO;
      let called = false;
      globalThis.fetch = async () => {
        called = true;
        return { ok: true, status: 202 };
      };
      const { reportToFleet } = await load();
      await reportToFleet({ counts: {} });

      assert.equal(called, false);
      assert.equal(written.join(''), '');
    } finally {
      restore();
    }
  });

  test('warns rather than posting when the token is missing', async () => {
    capture();
    try {
      process.env.APB_REPORT_TO = 'https://api.example.com/v1/fleet/reports';
      delete process.env.APB_ORG_TOKEN;
      let called = false;
      globalThis.fetch = async () => {
        called = true;
        return { ok: true, status: 202 };
      };
      const { reportToFleet } = await load();
      await reportToFleet({ counts: {} });

      assert.equal(called, false);
      assert.match(written.join(''), /::warning::/);
      assert.match(written.join(''), /org token/i);
    } finally {
      restore();
    }
  });

  test('posts the payload with the token', async () => {
    capture();
    try {
      process.env.APB_REPORT_TO = 'https://api.example.com/v1/fleet/reports';
      process.env.APB_ORG_TOKEN = 'apb_org_secret';
      process.env.GITHUB_REPOSITORY = 'acme/checkout-web';
      let seen;
      globalThis.fetch = async (url, init) => {
        seen = { url, init };
        return { ok: true, status: 202 };
      };
      const { reportToFleet } = await load();
      await reportToFleet({ counts: { behind: 2 }, severity: 'warning' });

      assert.equal(seen.url, 'https://api.example.com/v1/fleet/reports');
      assert.equal(seen.init.headers.authorization, 'Bearer apb_org_secret');
      const body = JSON.parse(seen.init.body);
      assert.equal(body.repo, 'acme/checkout-web');
      assert.equal(body.report.severity, 'warning');
    } finally {
      restore();
    }
  });

  /** The rule that matters: reporting failed, job still green. */
  test('warns and returns when the service refuses', async () => {
    capture();
    try {
      process.env.APB_REPORT_TO = 'https://api.example.com/v1/fleet/reports';
      process.env.APB_ORG_TOKEN = 'apb_org_wrong';
      globalThis.fetch = async () => ({ ok: false, status: 401 });
      const { reportToFleet } = await load();

      // Resolves — it does not throw, and nothing here can reach process.exit.
      await reportToFleet({ counts: {} });

      assert.match(written.join(''), /::warning::/);
      assert.match(written.join(''), /401/);
    } finally {
      restore();
    }
  });

  test('warns and returns when the network fails', async () => {
    capture();
    try {
      process.env.APB_REPORT_TO = 'https://api.example.com/v1/fleet/reports';
      process.env.APB_ORG_TOKEN = 'apb_org_secret';
      globalThis.fetch = async () => {
        throw new Error('getaddrinfo ENOTFOUND');
      };
      const { reportToFleet } = await load();

      await reportToFleet({ counts: {} });

      assert.match(written.join(''), /::warning::/);
      assert.match(written.join(''), /ENOTFOUND/);
    } finally {
      restore();
    }
  });
});
