import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { buildComment, buildSummary, headline, COMMENT_MARKER } from '../scripts/build-comment.mjs';

/** A `check --json` payload, clean unless overridden. */
function report(overrides = {}) {
  const counts = {
    current: 96,
    behind: 0,
    edited: 0,
    missing: 0,
    added: 0,
    orphaned: 0,
    ...(overrides.counts ?? {}),
  };
  return {
    schema: 1,
    project: 'checkout-web',
    generatorVersion: { recorded: '1.2.0', installed: '1.2.0' },
    behind: [],
    edited: [],
    missing: [],
    added: [],
    orphaned: [],
    newAiTools: [],
    severity: 'none',
    failOn: 'none',
    ok: true,
    ...overrides,
    counts,
  };
}

describe('headline', () => {
  test('says so plainly when nothing has drifted', () => {
    assert.equal(headline(report()), 'AI rules are current');
  });

  test('pluralises, because "1 files" in a bot comment reads as a bug', () => {
    assert.equal(headline(report({ counts: { behind: 1 } })), 'AI rules: 1 file behind');
    assert.equal(headline(report({ counts: { behind: 3 } })), 'AI rules: 3 files behind');
  });

  test('names every non-empty bucket', () => {
    const h = headline(report({ counts: { behind: 2, orphaned: 1, missing: 1, added: 4 } }));
    assert.match(h, /2 files behind/);
    assert.match(h, /1 orphaned file/);
    assert.match(h, /1 file missing/);
    assert.match(h, /4 new files/);
  });
});

describe('buildComment', () => {
  test('posts nothing for a clean repo', () => {
    // A bot that comments on every green PR to say "nothing to report" is a
    // bot people mute.
    assert.equal(buildComment(report()), null);
  });

  test('updates an existing comment to the all-clear once drift is fixed', () => {
    const body = buildComment(report(), { editingExisting: true });
    assert.ok(body);
    assert.match(body, /AI rules are current/);
  });

  test('keeps every block separated by a blank line, so Markdown does not fold them', () => {
    // Two adjacent non-empty lines become one paragraph, which silently ran
    // the all-clear sentence into the trailing note.
    for (const body of [
      buildComment(report({ counts: { edited: 1 }, edited: ['a.mdc'] }), { editingExisting: true }),
      buildComment(report({ counts: { behind: 1, edited: 1 }, behind: ['a.mdc'], edited: ['b.mdc'] })),
    ]) {
      const lines = body.split('\n');
      const subIndex = lines.findIndex((l) => l.startsWith('<sub>'));
      assert.ok(subIndex > 0);
      assert.equal(lines[subIndex - 1], '', `expected a blank line before: ${lines[subIndex]}`);
    }
  });

  test('always carries the marker, so the comment stays sticky', () => {
    const body = buildComment(report({ counts: { behind: 1 }, behind: ['a.mdc'] }));
    assert.ok(body.startsWith(COMMENT_MARKER));
  });

  test('lists drifted files and the command that fixes them', () => {
    const body = buildComment(
      report({
        counts: { behind: 2 },
        behind: ['.cursor/rules/nextjs.mdc', '.claude/skills/nextjs/SKILL.md'],
      }),
    );
    assert.match(body, /`\.cursor\/rules\/nextjs\.mdc`/);
    assert.match(body, /npx ai-project-bootstrap upgrade/);
  });

  test('truncates a long list rather than pasting hundreds of paths', () => {
    const files = Array.from({ length: 25 }, (_, i) => `.cursor/rules/mod-${i}.mdc`);
    const body = buildComment(report({ counts: { behind: 25 }, behind: files }));
    assert.match(body, /…and 15 more/);
    assert.ok(!body.includes('mod-20'));
  });

  test('states edited files as a guarantee, never as something to fix', () => {
    const body = buildComment(
      report({ counts: { behind: 1, edited: 2 }, behind: ['a.mdc'], edited: ['b.mdc', 'c.mdc'] }),
    );
    assert.match(body, /2 files you edited are preserved and will not be touched/);
    // Nothing in the comment should read as an instruction to revert them.
    assert.ok(!/revert/i.test(body));
  });

  test('does not promise upgrade will remove an orphan', () => {
    const body = buildComment(
      report({ counts: { orphaned: 1 }, orphaned: ['.cursor/rules/firebase.mdc'] }),
    );
    assert.match(body, /will not remove orphaned files/);
    // Orphans alone are not fixable by upgrade, so the command must not appear.
    assert.ok(!body.includes('npx ai-project-bootstrap upgrade\n```'));
  });

  test('offers upgrade when something it can fix sits alongside an orphan', () => {
    const body = buildComment(
      report({ counts: { behind: 1, orphaned: 1 }, behind: ['a.mdc'], orphaned: ['b.mdc'] }),
    );
    assert.match(body, /npx ai-project-bootstrap upgrade/);
    assert.match(body, /will not remove orphaned files/);
  });

  test('names both versions when the project was generated by an older release', () => {
    const body = buildComment(
      report({
        counts: { behind: 1 },
        behind: ['a.mdc'],
        generatorVersion: { recorded: '1.0.0', installed: '1.2.0' },
      }),
    );
    assert.match(body, /generated with v1\.0\.0, checked against v1\.2\.0/);
  });

  test('copes with a project generated before versions were recorded', () => {
    const body = buildComment(
      report({
        counts: { behind: 1 },
        behind: ['a.mdc'],
        generatorVersion: { recorded: null, installed: '1.2.0' },
      }),
    );
    assert.match(body, /checked against v1\.2\.0/);
    assert.ok(!body.includes('null'));
  });
});

describe('buildSummary', () => {
  test('reports every bucket, including the empty ones', () => {
    const summary = buildSummary(report({ counts: { behind: 2, edited: 1 } }));
    assert.match(summary, /\| Behind \| 2 \|/);
    assert.match(summary, /\| Orphaned \| 0 \|/);
    assert.match(summary, /\| Edited \(preserved\) \| 1 \|/);
    assert.match(summary, /checkout-web/);
  });
});
